### ISSUE TITLE
Milestone Maybe: Wine-Label show

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/amerine-wine-labels#3]
[wine-label-data]:https://github.com/UCDavisLibrary/wine-label-data
[wine-price-api]:https://github.com/UCDavisLibrary/wine-price-api
[wine-label-app]:https://github.com/ucd-library/wine-label-app

We need to develop the wine-price-api so that we have the information allow user edits of the wine-labels.  This is the next component of the label-this transformation.  More than likely this will become a set of milestones rather than a single milestone, This is just a placeholder for planning some of our major tasks.

Currently the following projects are possibly included;

- [wine-label-data] This stores some tools for building data from the wine-labels.  We should be able to use this getting the data into [wine-price-api], or maybe into another tool, like fedora.
- [wine-label-app] This is the start of an old project that allowed some editing to the wine labels.  There might be some leaflet editing code worth grabbing from that repo.
- [wine-price-api] We could add the label data to this postgres repository.

# Wine-Label Format

## Google Vision
I've been struggling with how to reformat the google-vision output, like converting to GeoJSON so it's Leaflet ready, but I realize that's a mistake.  We should probably leave it in it's native form, so eventually we can have the client spawn a Google Vision request directly, (hmm maybe not, maybe that has to be proxied, (For example if a user has 100 points, they can get an image visioned??))) 

Regardless, I think it's better to do the math, etc on the original Google Vision output.

# Editing Capability
Kimmy is reviewing some of the suggested editing patterns that I had from going from Google Vision results to a user edited set of label metadata.  One idea I has was that the user would see all the google vision edits, and combine them.  Kimmy has another idea, where the user would draw a box, and we would just include the text google vision found in that region.  The user would not need to know that Google Vision was involved at all.

The idea would be like if 80% of the Google vision rectangle overlapped, then we would include that text in the markup box.  This a pretty good idea, and we should be able to handle non-horizontal text pretty well too.
https://photos.google.com/photo/AF1QipN1VD3M5ZpuevDgwyoFrq7P3U17xp_fFwNgZdea

![image](https://user-images.githubusercontent.com/344953/28837455-9b156d54-76a1-11e7-9f90-40aa1858a764.png)

## Compare this process to Label-This
Since we actually have something like this completed for the label-this project, it would be pretty easy   to make a comparison to how well this would have done, by comparing the transcriptions from the Google Vision to those provided by our LabelThis project, and seeing how well we would have done in that case.

## Editing Notes for input
We wondered what hints to give users on how to add edits.  I suggested that we tell them to try and copy what they see, for example; if it's in ALL CAPS, then use All CAPS

![image](https://user-images.githubusercontent.com/344953/28837411-8079eea2-76a1-11e7-80db-f736f936d24e.png)

# Exporting ManageThis data.
Here are some queries that can help with transcription information.  We could consider making this postgres db readably available to some other hosts as well.
This database is located on managethis.library.ucdavis.edu. `psql managethis`

```{sql}
create view quinn.id_box as 
select identifier,
result->>'type' as type,
ARRAY[result->'region'->>'x',result->'region'->>'y',
             result->'region'->>'width',result->'region'->>'height']::decimal(6,2)[] 
from labels_mark;


create view quinn.mark_transcriptions as
with a as (
 select result->'parent_subject_id'->>'$oid' as mark,result->>'type' as type,
 jsonb_array_elements(result->'data'->'values')->>'value' as value 
 from labels_transcription
) 
select distinct mark,type,value from a;
```

## How to prioritize multiple marks.
One idea is to look more favorably on the most complex text (Somehow capture the use of UTF characters)

**Comment by wrenaria** [comment]
Here's a couple examples of what this might look like...

### Base view of label:
![ptv-label-baseview-100](https://user-images.githubusercontent.com/17831969/28847817-79afa106-76c5-11e7-8275-af692b74c598.jpg)
(I am not sure if including the original Google Vision marks would actually be helpful or just add confusion, since users won't necessarily have knowledge about the behind-the-scenes process for this. I'm inclined to think it might be confusing, but I'd like to know what you guys think and perhaps we can ask others as well.)

### Placing a Mark on a Label:
![ptv-label-markplacing-100](https://user-images.githubusercontent.com/17831969/28847858-94b072a0-76c5-11e7-9264-f48d15d52ea3.jpg)

### Selecting/Approving a Pending Label Mark
![ptv-label-markapproval-100](https://user-images.githubusercontent.com/17831969/28847976-07f6eb0e-76c6-11e7-9933-9e6223637df4.jpg)

You can find my more extensive working file here: 
https://drive.google.com/open?id=0B4y2_Xs4SL2-aEZUSk5lcjNKRUk
