### ISSUE TITLE
Required Metadata

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/amerine-wine-labels#6]
I have gleaned what information I could from the Amerine folder and index card information.  There are a few more tasks that need to be done.

- [X] The Collection Metadata needs to be filled out.  This is currently pretty much completely empty.  
- [X] I need input on the correct Rights Statement to use
- [X] We need to get fast headers from the existing keywords.

**Comment by EricNebeker** [comment]
@qjhart 
The rights statement should be "copyright not evaluated."

**Comment by EricNebeker** [comment]
@qjhart Here's what I've got so far on the collection metadata. The description can be fuller, but I'll either need to do more research on the provenance/history or we'll need to get someone more familiar with the collection to do it. I might have gone a little overboard on the keywords. 

Field | Metadata
-- | --
:title | Maynard Amerine's Wine Label Collection
:publisher | <lcna:no2008108707> , "University of California, Davis. General Library. Dept. of Special Collections" ;
:keywords | Wine, Wine labels, Red wines, White wines, Rose wines, Port wines, Sparkling wines
:subject fast | fast:1175881, fast:1175983, fast:1746284, fast:1746285, fast:1072014, fast:1128729
:license | Copyright not evaluated, http://rightsstatements.org/vocab/CNE/1.0/
:creator lcna: | n79065230
:creator | Amerine, Maynard
:datePublished | 2018
:keywords | 1874/1992, Wine, Wine labels, Red wines, White wines, Rose wines, Port wines, Sparkling wines
:description | Includes labels from domestic and foreign wines and spirits. Most labels date between 1874-1969, though some date as late as 1992.

**Comment by EricNebeker** [comment]
@qjhart 
How are we using the "LabelThis"/Google Vision data? Are we using the identifier as the title? It looks like the item metadata doesn't have a title field. This will be problematic for citations unless we have some other field map to title.

**Comment by qjhart** [comment]
@EricNebeker we have that data, but it's not structred, so it'd be hard to get a name from that.  IMO we are better off looking at some for the keywords;  the Wine Color, Type, and maybe country
So we'd have something like:

Red Burgandy - Still Red - fr-FR

Until we actually get better metadata for them .

**Comment by qjhart** [comment]
@EricNebeker Also, these collections to look nicer with a more complete description of the dataset.  This fills the left hand side, and a nice history or something would be good.

**Comment by EricNebeker** [comment]
@qjhart I have providing a fuller history on my to do list, but it'll take a little research. Other than that, are you asking for something like a narrative description of the collection and how it's put together?

**Comment by EricNebeker** [comment]
@qjhart Below is a longer description of the Amerine collection. I'm still not sure about the best option for item-level description. We could do a condensed version of the collection description that shows with all of the labels, or possibly provide folder information. The folder information is already in the keywords, though. Eventually we could use the full label text transcription. 

In 1935, Amerine was hired by the fledgling University of California, Davis’ newly formed Department of Viticulture and Enology to help establish a solid technical foundation for the California wine industry. As he traveled California and the world, educating and counseling winemakers on how to improve the quality of their wines, he collected over 5,000 wine labels. These labels tell the story of the growing wine industry during a pivotal time. The majority of the labels are from the 1930s and ’40s, but the collection spans nearly one hundred years, from the late 1800s to the 1960s.

Many of the labels in Amerine’s collection are from bottles he enjoyed at San Francisco’s Bohemian Club, and others were individual gifts, sometimes from private cellars. The collection is representative of the wines he preferred and had access to, and thus is heavy in California wines as well as an Amerine favorite — French wines.

Amerine pasted the labels into black spiral-bound notebooks, organized by region (usually country), divided into red or white, and in some cases further divided into sub-regions or ‘appellations.’ Some of the labels are annotated by Amerine, who gave the wine a letter grade or specified when, where and with whom the bottle might have been drunk.
