### ISSUE TITLE
Wine Label Names

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/amerine-wine-labels#7]
Provide some interium wine label information

**Comment by qjhart** [comment]
@EricNebeker Take a look at the Amerine Wine Label collection.  It's better, but could still use some TLC.

**Comment by EricNebeker** [comment]
@qjhart Ok. Gave it a quick look. Did you see the new, longer collection description I provided at :https://github.com/UCDavisLibrary/amerine-wine-labels/issues/6 ?
