### ISSUE TITLE
Review Item Level Metadata keywords

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/amerine-wine-labels#8]
Here are the current list keywords that exist in the item level metadata.  These should have their own fast headings, and some of them (Like the ones w/ Folder in the name) aren't probably very useful.

Name | Fast
| ---- | --- |
Additions from 1995 Folder
Additions Various Folder
Aperetifs & Liqueurs Folder
Apperitives and Liqueurs
Australia Folder
Austria Folder
Balkans Folder
Bordeaux Misc Red
Bordeaux White
Brandy
Brandy Folder
Burgundy Red
Burgundy White
California Red
California White
European Trip 1950-1952
Fortified Folder
France Folder
France Misc White
Germany Folder
Germany Frankenwein Folder
Germany Mosel Saar Ruwer Folder
Germany Naturrein-Unvergoren Folder
Germany Rheingau Folder
Germany Rheinhessen Folder
Germany Rheinpfalz Folder
Germany Sleiwerein Folder
Germany Sparkling Wine Folder
Germany Wurttemberg Folder
Italy
Italy Folder
Jamaica Rum Folder
Medoc Red
Misc Fortified
Misc Neck Labels Folder
Misc Table Wines
Moldova USSR folder
Moselle Misc German
North Africa Folder
Portugal Folder
Red Bordeaux (for book) folder
Removed from UC Reporters Notebook folder
Rhein Hessen Rheinfalz
Rhinegau
Rhone Misc & French Red
South Africa Folder
South America Folder
Spain
Spain - Catalonia Folder
Spain Folder
Spain Malaga Folder
Spain Navarra Folder
Spain Pontevedra Folder
Spain Rioja Rest to Check 1 Folder
Spain Rioja Rest to Check 2 Folder
Spain Rioja White Folder
Spain San Sadurni de Nova Folder
Spain Sherry Folder
Spain Valdepenas Folder
Spain Villafranca de Panades Folder
Spain Vino Blanco Folder
Spanish Misc Sweet and Fortified
Spanish Sherry
Spanish Table Wines Italy (Cypress and Greece)
Swiss
Switzerland Folder
UC Reporters Notebook
United States Folder
U.S. California Folder

**Comment by EricNebeker** [comment]
@qjhart Here are fast headings. Fast 1 and Fast 2 follow the order of terms in name field. E.g., Aperetifs & Liqueurs: Fast 1 is Aperetifs and Fast 2 is Liqueurs. Many of these are pairing a geographic heading and a topic heading. E.g. Burgundy Red: Fast 1 is Burgundy France and Fast 2 is Red Wines. The next comment is the list of Fast Headings I used to complete this list. Some of them were misspelled or had other oddities so I made my best guess. I couldn't identify a few of them.

Name | Fast 1 | Fast 2
-- | -- | --
Additions from 1995 Folder |   |  
Additions Various Folder |   |  
Aperetifs & Liqueurs Folder | fast/811244 | fast/999516
Apperitives and Liqueurs |   | fast/999516
Australia Folder | fast/1204543 |  
Austria Folder | fast/1204901 |  
Balkans Folder | fast/1241484 |  
Bordeaux Misc Red | fast/1759083 | fast/1746284
Bordeaux White | fast/1759083 | fast/1746285
Brandy | fast/837918 |  
Brandy Folder | fast/837918 |  
Burgundy Red | fast/1206081 | fast/1746284
Burgundy White | fast/1206081 | fast/1746285
California Red | fast/1204928 | fast/1746284
California White | fast/1204928 | fast/1746285
European Trip 1950-1952 | fast/1245064 |  
Fortified Folder | fast/933048 |  
France Folder | fast/1204289 |  
France Misc White | fast/1204289 | fast/1746285
Germany Folder | fast/1210272 |  
Germany Frankenwein Folder | fast/1244296 |  
Germany Mosel Saar Ruwer Folder | fast/1343792 |  
Germany Naturrein-Unvergoren Folder | fast/1210272 | fast/1745588
Germany Rheingau Folder | fast/1240997 |  
Germany Rheinhessen Folder | fast/1272622 |  
Germany Rheinpfalz Folder | fast/1272622 |  
Germany Sleiwerein Folder |   |  
Germany Sparkling Wine Folder | fast/1210272 | fast/1128729
Germany Wurttemberg Folder | fast/1205917 |  
Italy | fast/1204565 |  
Italy Folder | fast/1204565 |  
Jamaica Rum Folder | fast/1211575 | fast/1101236
Medoc Red | fast/1239757 | fast/1746284
Misc Fortified | fast/933048 |  
Misc Neck Labels Folder | fast/1175983 |  
Misc Table Wines | fast/1746582 |  
Moldova USSR folder | fast/1256791 | fast/1210281
Moselle Misc German | fast/1343792 | fast/1210272
North Africa Folder | fast/1239515 |  
Portugal Folder | fast/1208476 |  
Red Bordeaux (for book) folder | fast/1759083 | fast/1746284
Removed from UC Reporters Notebook folder |  
Rhein Hessen Rheinfalz | fast/1272622 |  
Rhinegau | fast/1240997 |  
Rhone Misc & French Red | fast/1214787 | fast/1746284
South Africa Folder | fast/1204616 |  
South America Folder | fast/1244515 |  
Spain | fast/1204303 |  
Spain - Catalonia Folder | fast/1206043 |  
Spain Folder | fast/1204303 |  
Spain Malaga Folder | fast/1206680 |  
Spain Navarra Folder | fast/1262022 |  
Spain Pontevedra Folder | fast/1330577 |  
Spain Rioja Rest to Check 1 Folder | fast/1207340 |  
Spain Rioja Rest to Check 2 Folder | fast/1207340 |  
Spain Rioja White Folder | fast/1207340 | fast/1746285
Spain San Sadurni de Nova Folder | fast/1233917 |  
Spain Sherry Folder | fast/1204303 | fast/1115874
Spain Valdepenas Folder | fast/1223955 |  
Spain Villafranca de Panades Folder | fast/1215566 |  
Spain Vino Blanco Folder | fast/1204303 | fast/1746285
Spanish Misc Sweet and Fortified | fast/1204303 | fast/933048
Spanish Sherry | fast/1204303 | fast/1115874
Spanish Table Wines Italy (Cypress and Greece) | fast/1204303 | fast/1746582 | fast/1205213 | fast/1208380
Swiss | fast/1205401 |  
Switzerland Folder | fast/1205401 |  
UC Reporters Notebook |   |  
United States Folder | fast/1204155 |  
U.S. California Folder | fast/1204928 |

**Comment by EricNebeker** [comment]
Fast heading and URI | abbreviated Fast ID | Use in Title
-- | -- | --
Africa, North: http://id.worldcat.org/fast/1239515 | fast/1239515 | Use
Aperitifs: http://id.worldcat.org/fast/811244 | fast/811244 | Use
Apperitives z Aperitifs: http://id.worldcat.org/fast/811244 | fast/811244 | Don't Use
Australia: http://id.worldcat.org/fast/1204543 | fast/1204543 | Use
Austria: http://id.worldcat.org/fast/1204901 | fast/1204901 | Use
Balkans: http://id.worldcat.org/fast/1241484 | fast/1241484 | Use
Brandy: http://id.worldcat.org/fast/837918 | fast/837918 | Use
California: http://id.worldcat.org/fast/1204928 | fast/1204928 | Use
Cyprus: http://id.worldcat.org/fast/1205213 | fast/1205213 | Use
Europe: http://id.worldcat.org/fast/1245064 | fast/1245064 | Use
Europe—Moselle river region:http://id.worldcat.org/fast/1343792 | fast/1343792 | Use
Fortified wines: http://id.worldcat.org/fast/933048 | fast/933048 | Use
France--Bordeaux Region (Aquitaine): http://id.worldcat.org/fast/1759083 | fast/1759083 | Use
France—Burgundy: http://id.worldcat.org/fast/1206081 | fast/1206081 | Use
France—Rhone: http://id.worldcat.org/fast/1214787 | fast/1214787 | Use
France--Medoc: http://id.worldcat.org/fast/1239757 | fast/1239757 | Use
France: http://id.worldcat.org/fast/1204289 | fast/1204289 | Use
Germany--Franconia: http://id.worldcat.org/fast/1244296 | fast/1244296 | Use
Germany--Rheingau: http://id.worldcat.org/fast/1240997 | fast/1240997 | Use
Germany--Rheinhessen-Pfalz: http://id.worldcat.org/fast/1272622 | fast/1272622 | Use
Germany--Württemberg: http://id.worldcat.org/fast/1205917 | fast/1205917 | Use
Germany: http://id.worldcat.org/fast/1210272 | fast/1210272 | Use
Greece: http://id.worldcat.org/fast/1208380 | fast/1208380 | Use
Italy: http://id.worldcat.org/fast/1204565 | fast/1204565 | Use
Jamaica: http://id.worldcat.org/fast/1211575 | fast/1211575 | Use
Liqueurs: http://id.worldcat.org/fast/999516 | fast/999516 | Use
Moldova: http://id.worldcat.org/fast/1256791 | fast/1256791 | Use
Port wines: http://id.worldcat.org/fast/1072014 | fast/1072014 | Use
Portugal: http://id.worldcat.org/fast/1208476 | fast/1208476 | Use
Red wines: http://id.worldcat.org/fast/1746284 | fast/1746284 | Use
Rose wines: http://id.worldcat.org/fast/1202309 | fast/1202309 | Use
Rum: http://id.worldcat.org/fast/1101236 | fast/1101236 | Use
Sherry: http://id.worldcat.org/fast/1115874 | fast/1115874 | Use
South Africa: http://id.worldcat.org/fast/1204616 | fast/1204616 | Use
South America: http://id.worldcat.org/fast/1244515 | fast/1244515 | Use
Soviet Union: http://id.worldcat.org/fast/1210281 | fast/1210281 | Use
Spain Valdepenas: http://id.worldcat.org/fast/1223955 | fast/1223955 | Use
Spain Villafranca de Panades: http://id.worldcat.org/fast/1215566 | fast/1215566 | Use
Spain--Barranca de Navarra Region: http://id.worldcat.org/fast/1262022 | fast/1262022 | Use
Spain--Catalonia: http://id.worldcat.org/fast/1206043 | fast/1206043 | Use
Spain--Málaga: http://id.worldcat.org/fast/1206680 | fast/1206680 | Use
Spain--Pontevedra (Province): http://id.worldcat.org/fast/1330577 | fast/1330577 | Use
Spain--San Sadurní de Noya: http://id.worldcat.org/fast/1233917 | fast/1233917 | Use
Spain—La Rioja: http://id.worldcat.org/fast/1207340 | fast/1207340 | Use
Spain: http://id.worldcat.org/fast/1204303 | fast/1204303 | Use
Sparkling wines: http://id.worldcat.org/fast/1128729 | fast/1128729 | Use
Switzerland: http://id.worldcat.org/fast/1205401 | fast/1205401 | Use
Syrah: http://id.worldcat.org/fast/1746226 | fast/1746226 | Use
Table wines: http://id.worldcat.org/fast/1746582 | fast/1746582 | Use
Non-alcholic Wines: http://id.worldcat.org/fast/1745588 | fast/1745588 | Use
United States: http://id.worldcat.org/fast/1204155 | fast/1204155 | Use
White wines: http://id.worldcat.org/fast/1746285 | fast/1746285 | Use
Wine industry—Location: http://id.worldcat.org/fast/1175973 | fast/1175973 | Don't Use
Wine industry—Marketing: http://id.worldcat.org/fast/1175974 | fast/1175974 | Don't Use
Wine labels in art: http://id.worldcat.org/fast/1201856 | fast/1201856 | Don't Use
Wine labels: http://id.worldcat.org/fast/1175983 | fast/1175983 | Don't Use
Wine—Color: http://id.worldcat.org/fast/1200405 | fast/1200405 | Don't Use
Wine—varieties: http://id.worldcat.org/fast/1175905 | fast/1175905 | Don't Use
Wine: http://id.worldcat.org/fast/1175881 | fast/1175881 | Don't Use

**Comment by qjhart** [comment]
@EricNebeker, this is great.  That's.  I'll rerun the metadata creation tool, and I'll include this information as well.

**Comment by EricNebeker** [comment]
@qjhart Here's the use/don't use list. It'll be interesting to see how these look.
